version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ./tmp/bundle-data:/bundle
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=/bundle
    depends_on:
      - db
